[build]
builder = "nixpacks"
nixpacksPlan = "python"

[deploy]
startCommand = "gunicorn app:app --bind 0.0.0.0:$PORT"
restartPolicyType = "ON_FAILURE"

[phases.setup]
nixPkgs = ["python310", "gcc"]

[phases.install]
cmds = ["pip install -r requirements.txt"]